trigger:
  branches:
    include:
      - main

pool:
  name: SecureBankAgentPool

steps:
  - checkout: self
    displayName: Checkout GitHub source code

  - script: |
      java -version
      mvn -version
      mvn --batch-mode clean package
    displayName: Build and test SecureBank with Maven

  - task: CopyFiles@2
    displayName: Copy application JAR
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target'
      Contents: '*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: Publish SecureBank build artifact
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'securebank-application'

  - task: Docker@2
    displayName: Build and push SecureBank Docker image
    inputs:
      containerRegistry: 'acrsecurebankkeerthi'
      repository: 'securebank-app'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest